### PR TITLE
Change variable substitution method

### PR DESCRIPTION
**Pull request by jtpalmer**
## Description

See ubccr/xdmod#1448

## Motivation and Context

https://app.asana.com/0/342819846538629/1185671232325739/f

## Tests performed

Tested manually using the job viewer.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jtpalmer** [comment]
Do we want to keep this rule enabled globally?

```
2221:19  NEW ERROR    Unexpected template string expression. (no-template-curly-in-string)
```

**Review by jpwhite4 — APPROVED** [review]

**Comment by jpwhite4** [comment]
Also we should take the opportunity to remove the now unneeded config parser code from the etl library.
Which is in the  parseuri: function in config.js

**Comment by jtpalmer** [comment]
The `config://` syntax is still used in a couple places: https://github.com/ubccr/xdmod-supremm/blob/xdmod9.5/configuration/etl/etl_tables.d/jobefficiency/jobefficiency_by_day.json#L42

I'll change those and then the `parseuri` function.

**Comment by jtpalmer** [comment]
@jpwhite4 The ETL table definitions do not have the same variable substitutions available so more changes will be necessary.

**Review by jpwhite4 — DISMISSED** [review]

**Review by jpwhite4 — APPROVED** [review]

**Pull request merged**
